### ISSUE TITLE
Might be another issue of supporting Python 3

### ISSUE THREAD

**Issue by fbukevin** [djacobs/PyAPNs#179] opened 2016-10-13 17:02 UTC
I just import apns and get the error:

```
Python 3.5.0 (default, Sep 23 2015, 04:41:38) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import apns
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1136, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1112, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1093, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 530, in spec_from_file_location
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/apns-2.0.1-py3.5.egg/apns.py", line 218
    except ssl.SSLError, err:
                       ^
SyntaxError: invalid syntax
```

Also, when I used sample code in README i got the same error:

```
Traceback (most recent call last):
  File "test_apns.py", line 6, in <module>
    from apns import APNs, Frame, Payload
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1136, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1112, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1093, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 530, in spec_from_file_location
  File "/Users/veck/Desktop/.../venv/lib/python3.5/site-packages/apns-2.0.1-py3.5.egg/apns.py", line 218
    except ssl.SSLError, err:
                       ^
SyntaxError: invalid syntax
```

**Comment by fbukevin** [comment] 2016-10-13 17:19
I found [this commit](https://github.com/djacobs/PyAPNs/commit/fce9e33c62a0cef8eebcd8b1a293d66be0b45480) had fixed this problem. But I don't have idea why it seems that it was removed from current code?

**Comment by ExplodingCabbage** [comment] 2016-10-13 19:52
It hasn't been removed; there's just never been a release on PyPi that contained that commit. Closing as a duplicate of https://github.com/djacobs/PyAPNs/issues/163; we need @djacobs to make another release.

**Closed by ExplodingCabbage** 2016-10-13 19:52 UTC
