### ISSUE TITLE
Not Supporting python 3

### ISSUE THREAD

**Issue by MajjigaDeepak** [djacobs/PyAPNs#166] opened 2016-05-11 12:32 UTC
PyAPNs is not supporting python version 3.Getting some syntax error ^ .Could you please guide me in resolving this or any alternative ?

**Comment by AhnSeongHyun** [comment] 2016-05-11 14:37
Fork this project and modify yourself. I did.

**Comment by MajjigaDeepak** [comment] 2016-05-11 15:16
Thanks AhnSeognHyun,

I Forked.Could you please guide me what & where i have to modify the code?

**Comment by jakubczaplicki** [comment] 2016-05-13 17:13
+1

**Comment by ExplodingCabbage** [comment] 2016-05-14 09:54
Duplicate of https://github.com/djacobs/PyAPNs/issues/85

**Closed by ExplodingCabbage** 2016-05-14 09:54 UTC
